<?php

/**
 *  Implements hook_field_widget_form_alter().
 */
function file_replace_field_widget_form_alter(&$element, &$form_state, $context) {
  if ($context['field']['type'] == 'file') {
    foreach (element_children($element) as $key) {
      $element[$key]['#upload_validators']['file_replace_overwrite_existing'] = array($context);
    }
  }
}

/**
 * Checks if the new file matches an existing file on the node and prevents
 * name mangling and a new file from being created if this is the case
 */
function file_replace_overwrite_existing($file, $context) {
  $destination_directory = drupal_dirname($file->destination);
  $unmangled_destination = $destination_directory . '/' . $file->filename;
  foreach ($context['items'] as $delta => $file_info) {
    if (isset($file_info['uri']) && $file_info['uri'] === $unmangled_destination) {
      $file->destination = $file_info['uri'];
      $file->fid = $file_info['fid'];
      break;
    }
  }
  return array();
}